[add] support saving all page of a BI Data Table
kaiyuanshe/KYS-service pull request #20
Opened 2023-10-18 17:35 UTC by wangrunlin

1. [add] support saving all page of a BI Data Table(Close #8)

2023-10-18 17:37 UTC, wangrunlin commented
目前请求数据还没有跑通
```ts
{ code: 91402, msg: 'NOTEXIST', data: {} }
```

2023-10-19 04:13 UTC, TechQuery requested changes

2023-10-19 04:13 UTC, TechQuery commented on src/controller/Crawler.ts
> +    }
老代码先不移动，减少差异对比。

2023-10-19 04:13 UTC, TechQuery commented on src/controller/Crawler.ts
> +            this.savePage({ source: fields['link'] + '', rootSelector });
```suggestion
            await this.savePage({ source: fields['link'] + '', rootSelector });
```

2023-10-19 04:13 UTC, TechQuery commented on src/model/Crawler.ts
> +    id?: string;
```suggestion
    id: string;
```

2024-01-02 16:08 UTC, wangrunlin commented
@CodiumAI-Agent /review

2024-01-02 16:09 UTC, CodiumAI-Agent commented
## PR Analysis

- 🎯 **Main theme:** Adding support for saving all pages of a BI Data Table
- 📝 **PR summary:** This PR introduces the capability to save all pages of a BI Data Table. It does this by modifying the CrawlerController and the associated models. The changes include the addition of new methods and the modification of existing ones to support the new functionality.
- 📌 **Type of PR:** Enhancement
- 🧪 **Relevant tests added:** No
- ⏱️ **Estimated effort to review [1-5]:** 4, because the PR involves changes in multiple methods and classes, and the logic is not straightforward. Understanding the context and the impact of these changes requires a good understanding of the existing codebase.
- 🔒 **Security concerns:** No
## PR Feedback



<strong>💡 General suggestions:</strong> The PR seems to be well-structured and the changes are logically grouped. However, it would be beneficial to add tests to ensure the new functionality works as expected and does not introduce regressions. Additionally, it would be helpful to add comments to complex sections of the code to improve maintainability.


<details><summary> <strong>🤖 Code feedback:</strong></summary><hr><table><tr><td>relevant file</td><td>src/controller/Crawler.ts</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td><strong>

Consider handling exceptions in the `saveFiles` method. If the file download or upload fails, it could lead to unexpected behavior. [important]</strong></td></tr><tr><td>relevant line</td><td>'+    async *saveFiles(fields: TableRecordFields) {'</td></tr></table><hr><table><tr><td>relevant file</td><td>src/controller/Crawler.ts</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td><strong>

It would be a good idea to add logging for any errors that occur during the `savePage` method. This would make it easier to debug any issues that arise. [medium]</strong></td></tr><tr><td>relevant line</td><td><a href=https://github.com/kaiyuanshe/KYS-service/pull/20/files#diff-c878d474ff2f267a60a89e1d3327439f827dc917fb6c139dbf5fdd8a8e32ad30R54>'+    async savePage({ source, rootSelector }: PageTask) {'</a></td></tr></table><hr><table><tr><td>relevant file</td><td>src/model/Crawler.ts</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td><strong>

It seems like the `LarkBaseTableRecordFileModel` class is extending `LarkBaseTableModel` but only adding one field. Consider whether this inheritance is necessary or if the two classes could be combined. [medium]</strong></td></tr><tr><td>relevant line</td><td><a href=https://github.com/kaiyuanshe/KYS-service/pull/20/files#diff-d9dec090865749b482dcf96037802d79c61ab4964dbd7bfa3b97abad4dd2ab60R37>'+export class LarkBaseTableRecordFileModel extends LarkBaseTableModel {'</a></td></tr></table><hr><table><tr><td>relevant file</td><td>src/controller/Crawler.ts</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td><strong>

It might be beneficial to add some error handling or checks in the `createLarkBaseTablePageTask` method to ensure that the `getAll` method returns a valid result. [medium]</strong></td></tr><tr><td>relevant line</td><td><a href=https://github.com/kaiyuanshe/KYS-service/pull/20/files#diff-c878d474ff2f267a60a89e1d3327439f827dc917fb6c139dbf5fdd8a8e32ad30R99>'+    async createLarkBaseTablePageTask('</a></td></tr></table><hr></details>



<details> <summary><strong>✨ Usage tips:</strong></summary><hr> 

> Tag me in a comment '@CodiumAI-Agent' and add one of the following commands:  
> - **/review**: Request a review of your Pull Request.   
> - **/describe**: Update the PR title and description based on the contents of the PR.   
> - **/improve [--extended]**: Suggest code improvements. Extended mode provides a higher quality feedback.   
> - **/ask \<QUESTION\>**: Ask a question about the PR.   
> - **/update_changelog**: Update the changelog based on the PR's contents.   
> - **/add_docs** 💎: Generate docstring for new components introduced in the PR.   
> - **/generate_labels** 💎: Generate labels for the PR based on the PR's contents.   
> - **/analyze** 💎: Automatically analyzes the PR, and presents changes walkthrough for each component.   

>See the [tools guide](https://github.com/Codium-ai/pr-agent/blob/main/docs/TOOLS_GUIDE.md) for more details.
>To edit any configuration parameter from the [configuration.toml](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml), add --config_path=new_value.  
>For example: /review --pr_reviewer.extra_instructions="focus on the file: ..."    
>To list the possible configuration parameters, add a **/config** comment.   

</details>

2024-01-02 16:10 UTC, wangrunlin commented
@CodiumAI-Agent /describe

2024-01-02 16:10 UTC, CodiumAI-Agent commented
## Title

Enhancements to Crawler Controller and Model

___
## Type
Enhancement


___

## Description
This PR introduces significant enhancements to the `CrawlerController` and the `Crawler` model:
- The `saveFiles` method has been moved up in the `CrawlerController` class.
- A new method `savePage` has been added to the `CrawlerController` class.
- The `createPageTask` method in the `CrawlerController` class now calls `savePage`.
- A new method `createLarkBaseTablePageTask` has been added to the `CrawlerController` class.
- The `createLarkBaseTableRecordFileTask` and `createLarkBaseTableFileTask` methods in the `CrawlerController` class have been updated to reflect changes in the model.
- The `PageTask` class in the `Crawler` model now extends a new `PageSelector` class.
- The `LarkBaseTableFileTask` class in the `Crawler` model has been renamed to `LarkBaseTable`.
- The `LarkBaseTableRecordFileTask` class in the `Crawler` model has been renamed to `LarkBaseTableRecord`.
- The `LarkBaseTableRecordFileModel` and `LarkBaseTableFileModel` classes in the `Crawler` model have been updated to reflect these changes.


___

## PR changes walkthrough
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>2 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>Crawler.ts&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        src/controller/Crawler.ts<br><br>

**The `CrawlerController` class has been significantly <br>refactored. The `saveFiles` method has been moved up in the <br>class. A new method `savePage` has been added. The <br>`createPageTask` method now calls `savePage`. A new method <br>`createLarkBaseTablePageTask` has been added. The <br>`createLarkBaseTableRecordFileTask` and <br>`createLarkBaseTableFileTask` methods have been updated to <br>reflect changes in the model.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/kaiyuanshe/KYS-service/pull/20/files#diff-c878d474ff2f267a60a89e1d3327439f827dc917fb6c139dbf5fdd8a8e32ad30"> +65/-29</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>Crawler.ts&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        src/model/Crawler.ts<br><br>

**The `PageTask` class now extends a new `PageSelector` class. <br>The `LarkBaseTableFileTask` class has been renamed to <br>`LarkBaseTable`. The `LarkBaseTableRecordFileTask` class has <br>been renamed to `LarkBaseTableRecord`. The <br>`LarkBaseTableRecordFileModel` and `LarkBaseTableFileModel` <br>classes have been updated to reflect these changes.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/kaiyuanshe/KYS-service/pull/20/files#diff-d9dec090865749b482dcf96037802d79c61ab4964dbd7bfa3b97abad4dd2ab60"> +13/-12</a></td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

2024-01-02 16:22 UTC, wangrunlin commented on src/controller/Crawler.ts
> +    }
@CodiumAI-Agent /ask What's this?

2024-10-14 10:01 UTC, wangrunlin commented
@TechQuery mobx-lark 升级到 2.0.0-rc.3 后，运行 `pnpm dev` 会出现以下报错
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /workspace/KYS-service/node_modules/.pnpm/native-file-system-adapter@3.0.1/node_modules/native-file-system-adapter/src/es6.js from /workspace/KYS-service/node_modules/.pnpm/mobx-restful@1.0.1_jsdom@22.1.0_mobx@5.15.7_typescript@5.3.3/node_modules/mobx-restful/dist/index.js not supported.
Instead change the require of es6.js in /workspace/KYS-service/node_modules/.pnpm/mobx-restful@1.0.1_jsdom@22.1.0_mobx@5.15.7_typescript@5.3.3/node_modules/mobx-restful/dist/index.js to a dynamic import() which is available in all CommonJS modules.
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-2701919942264728.js:114:20)
    at Object.nodeDevHook [as .js] (/workspace/KYS-service/node_modules/.pnpm/ts-node-dev@2.0.0_@types+node@18.19.3_typescript@5.3.3/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/workspace/KYS-service/node_modules/.pnpm/mobx-restful@1.0.1_jsdom@22.1.0_mobx@5.15.7_typescript@5.3.3/node_modules/mobx-restful/dist/index.js:1:1048)
    at Module._compile (/workspace/KYS-service/node_modules/.pnpm/source-map-support@0.5.21/node_modules/source-map-support/source-map-support.js:568:25)
[ERROR] 09:58:34 Error: require() of ES Module /workspace/KYS-service/node_modules/.pnpm/native-file-system-adapter@3.0.1/node_modules/native-file-system-adapter/src/es6.js from /workspace/KYS-service/node_modules/.pnpm/mobx-restful@1.0.1_jsdom@22.1.0_mobx@5.15.7_typescript@5.3.3/node_modules/mobx-restful/dist/index.js not supported.
Instead change the require of es6.js in /workspace/KYS-service/node_modules/.pnpm/mobx-restful@1.0.1_jsdom@22.1.0_mobx@5.15.7_typescript@5.3.3/node_modules/mobx-restful/dist/index.js to a dynamic import() which is available in all CommonJS modules.
```

目前计划更新到弃用的版本 `1.1.1`

2024-10-14 10:14 UTC, TechQuery commented
> @TechQuery mobx-lark 升级到 2.0.0-rc.3 后，运行 `pnpm dev` 会出现以下报错
> 
> ```
> Error [ERR_REQUIRE_ESM]: require() of ES Module /workspace/KYS-service/node_modules/.pnpm/native-file-system-adapter@3.0.1/node_modules/native-file-system-adapter/src/es6.js from /workspace/KYS-service/node_modules/.pnpm/mobx-restful@1.0.1_jsdom@22.1.0_mobx@5.15.7_typescript@5.3.3/node_modules/mobx-restful/dist/index.js not supported.
> Instead change the require of es6.js in /workspace/KYS-service/node_modules/.pnpm/mobx-restful@1.0.1_jsdom@22.1.0_mobx@5.15.7_typescript@5.3.3/node_modules/mobx-restful/dist/index.js to a dynamic import() which is available in all CommonJS modules.
>     at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-2701919942264728.js:114:20)
>     at Object.nodeDevHook [as .js] (/workspace/KYS-service/node_modules/.pnpm/ts-node-dev@2.0.0_@types+node@18.19.3_typescript@5.3.3/node_modules/ts-node-dev/lib/hook.js:63:13)
>     at Object.<anonymous> (/workspace/KYS-service/node_modules/.pnpm/mobx-restful@1.0.1_jsdom@22.1.0_mobx@5.15.7_typescript@5.3.3/node_modules/mobx-restful/dist/index.js:1:1048)
>     at Module._compile (/workspace/KYS-service/node_modules/.pnpm/source-map-support@0.5.21/node_modules/source-map-support/source-map-support.js:568:25)
> [ERROR] 09:58:34 Error: require() of ES Module /workspace/KYS-service/node_modules/.pnpm/native-file-system-adapter@3.0.1/node_modules/native-file-system-adapter/src/es6.js from /workspace/KYS-service/node_modules/.pnpm/mobx-restful@1.0.1_jsdom@22.1.0_mobx@5.15.7_typescript@5.3.3/node_modules/mobx-restful/dist/index.js not supported.
> Instead change the require of es6.js in /workspace/KYS-service/node_modules/.pnpm/mobx-restful@1.0.1_jsdom@22.1.0_mobx@5.15.7_typescript@5.3.3/node_modules/mobx-restful/dist/index.js to a dynamic import() which is available in all CommonJS modules.
> ```
> 
> 目前计划更新到弃用的版本 `1.1.1`

该包的 ReadMe 有写解决方案，之前开会也讲过。

2024-10-15 07:39 UTC, wangrunlin commented
@TechQuery 目前主分支代码流程跑不通，疑似 `web-fetch` 的 `loadPage` 函数有问题，我单独建立一个测试文件没有，但是在该服务中集成无法获取到 `document`。

![image](https://github.com/user-attachments/assets/752e98da-b664-4433-b934-208bc0748719)

2024-10-15 07:55 UTC, TechQuery commented
> @TechQuery 目前主分支代码流程跑不通，疑似 `web-fetch` 的 `loadPage` 函数有问题，我单独建立一个测试文件没有，但是在该服务中集成无法获取到 `document`。
> 
> ![image](https://github.com/user-attachments/assets/752e98da-b664-4433-b934-208bc0748719)

`try {} catch {}` 这个函数看看

2024-10-15 07:58 UTC, TechQuery requested changes

2024-10-15 07:58 UTC, TechQuery commented on src/controller/Crawler.ts
> +    }
和上面的方法位置换一下，看看能不能减少变更差异对比。

2024-10-18 09:29 UTC, wangrunlin commented
> > @TechQuery 目前主分支代码流程跑不通，疑似 `web-fetch` 的 `loadPage` 函数有问题，我单独建立一个测试文件没有，但是在该服务中集成无法获取到 `document`。
> > ![image](https://private-user-images.githubusercontent.com/64216877/376505344-752e98da-b664-4433-b934-208bc0748719.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDQwNDAsIm5iZiI6MTcyOTI0Mzc0MCwicGF0aCI6Ii82NDIxNjg3Ny8zNzY1MDUzNDQtNzUyZTk4ZGEtYjY2NC00NDMzLWI5MzQtMjA4YmMwNzQ4NzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA5MjkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NDUyNGUwMTIyOWYxODg5ZTNmYmQ1YWQ2NTA1MzVjOGZkZGY5YjM3YmNiYTFmNmI1ZTBlYTM4Yzg4YmQwZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LaGN1Te1M2W1lON16o7KRb_w_BzfMTqaNXXae4B8UQ0)
> 
> `try {} catch {}` 这个函数看看

```
  <-- POST /crawler/task/page
TimeoutError: Timed out after waiting 30000ms
    at /Users/leo/code/kaiyuanshe/KYS-service/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/src/common/util.ts:322:17
    at /Users/leo/code/kaiyuanshe/KYS-service/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:3986:35
    at OperatorSubscriber2._this._next (/Users/leo/code/kaiyuanshe/KYS-service/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:1055:13)
    at OperatorSubscriber2.Subscriber2.next (/Users/leo/code/kaiyuanshe/KYS-service/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:678:16)
    at AsyncAction2.<anonymous> (/Users/leo/code/kaiyuanshe/KYS-service/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:4863:24)
    at AsyncAction2._execute (/Users/leo/code/kaiyuanshe/KYS-service/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:1974:16)
    at AsyncAction2.execute (/Users/leo/code/kaiyuanshe/KYS-service/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:1963:26)
    at AsyncScheduler2.flush (/Users/leo/code/kaiyuanshe/KYS-service/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:2235:30)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7) {
  [cause]: undefined
}
  --> POST /crawler/task/page 500 31s 851b
```
<img width="1552" alt="image" src="https://github.com/user-attachments/assets/f7365f11-4018-493f-bd2b-fe388edb04b0">

2024-10-18 11:21 UTC, TechQuery commented
> ```
>   <-- POST /crawler/task/page
> TimeoutError: Timed out after waiting 30000ms
>     at /Users/leo/code/kaiyuanshe/KYS-service/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/src/common/util.ts:322:17
>     at /Users/leo/code/kaiyuanshe/KYS-service/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:3986:35
>     at OperatorSubscriber2._this._next (/Users/leo/code/kaiyuanshe/KYS-service/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:1055:13)
>     at OperatorSubscriber2.Subscriber2.next (/Users/leo/code/kaiyuanshe/KYS-service/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:678:16)
>     at AsyncAction2.<anonymous> (/Users/leo/code/kaiyuanshe/KYS-service/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:4863:24)
>     at AsyncAction2._execute (/Users/leo/code/kaiyuanshe/KYS-service/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:1974:16)
>     at AsyncAction2.execute (/Users/leo/code/kaiyuanshe/KYS-service/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:1963:26)
>     at AsyncScheduler2.flush (/Users/leo/code/kaiyuanshe/KYS-service/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:2235:30)
>     at listOnTimeout (node:internal/timers:573:17)
>     at processTimers (node:internal/timers:514:7) {
>   [cause]: undefined
> }
>   --> POST /crawler/task/page 500 31s 851b
> ```
> 
> <img alt="image" width="1552" src="https://private-user-images.githubusercontent.com/64216877/377810539-f7365f11-4018-493f-bd2b-fe388edb04b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNTA1NTEsIm5iZiI6MTcyOTI1MDI1MSwicGF0aCI6Ii82NDIxNjg3Ny8zNzc4MTA1MzktZjczNjVmMTEtNDAxOC00OTNmLWJkMmItZmUzODhlZGIwNGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDExMTczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNGJiM2I0YzEzOTQ5NTZkYjg2YjZiZjkyMTZhOTNkNWUwZjcxNDVhNTM5MTE4YjI3MWFmNzMyNjEwMGM1ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.56PLSyUaprSZE2NvyRJqWmcwsn3_307unYAjsrYg-9o">

经查是较新版 Puppteer core 无法正常启动本地浏览器，但升级到最新版 bug 依旧：https://github.com/puppeteer/puppeteer/issues/13012

2024-11-11 21:21 UTC, TechQuery approved these changes

2024-11-11 23:04 UTC, merged