Db management backend web
kaiyuanshe/KYS-service pull request #26
Opened 2024-08-19 02:40 UTC by luojiyin1987

Closed #25

2024-08-19 02:45 UTC, luojiyin1987 commented
@TechQuery   还要确定 dashpress 的文件存放地方吗？  现在要传输两个 Docker 镜像文件，  GitHub action 还要调整

2024-08-19 04:17 UTC, TechQuery requested changes

2024-08-19 04:17 UTC, TechQuery commented on docker-compose.yml
> +            - postgres
API 服务也要依赖，因为程序启动后还可能会做数据库表结构同步。

2024-08-19 04:17 UTC, TechQuery commented on docker-compose.yml
> +        image: kaiyuanshe/dashpress
没有发布到 DockerHub 或在流水线打包后手动导入是不能写镜像名的。

2024-08-19 07:25 UTC, luojiyin1987 commented on docker-compose.yml
> +        image: kaiyuanshe/dashpress
所以我在上面说， 调整 GitHub action， 导出两个 Docker  镜像。

2024-08-19 15:54 UTC, TechQuery commented on docker-compose.yml
> +        image: kaiyuanshe/dashpress
> 所以我在上面说， 调整 GitHub action， 导出两个 Docker  镜像。

手机客户端上没法同时看到内外部评论，看漏了。

2024-08-19 15:55 UTC, TechQuery commented
> @TechQuery   还要确定 dashpress 的文件存放地方吗？  现在要传输两个 Docker 镜像文件，  GitHub action 还要调整

独立一个公共镜像推到 DockerHub 再引用。

2024-08-20 12:32 UTC, TechQuery requested changes
`.env` 的内容是什么？需要放在配置仓库吧

2024-08-20 12:32 UTC, TechQuery commented on Dockerfile-dashpress
> +FROM node:18-slim
可以删了

2024-08-20 12:36 UTC, luojiyin1987 commented
> `.env` 的内容是什么？需要放在配置仓库吧

就是 pg 的 JWT_SECRET 密码， 本地没有的话， 无法正常启动 pg 容器。

2024-08-20 12:55 UTC, TechQuery commented
> 就是 pg 的 JWT_SECRET 密码， 本地没有的话， 无法正常启动 pg 容器。

我说的是数据库密码、连接字符串等值如何定义和传入 DashPress 镜像？

2024-08-20 13:00 UTC, luojiyin1987 commented
> > 就是 pg 的 JWT_SECRET 密码， 本地没有的话， 无法正常启动 pg 容器。
> 
> 我说的是数据库密码、连接字符串等值如何定义和传入 DashPress 镜像？

没有， DashPress 本身没留有环境变量的入口。  所以挂载本地文件夹，第一次配置好了，就保存在文件夹 `./dashpress/app` 里。

2024-08-20 13:07 UTC, TechQuery commented
> 没有， DashPress 本身没留有环境变量的入口。  所以挂载本地文件夹，第一次配置好了，就保存在文件夹 `./dashpress/app` 里。

在 Docker 里如何进行首次配置？

2024-08-20 13:10 UTC, luojiyin1987 commented
> > 没有， DashPress 本身没留有环境变量的入口。  所以挂载本地文件夹，第一次配置好了，就保存在文件夹 `./dashpress/app` 里。
> 
> 在 Docker 里如何进行首次配置？

登录DashPress 的web 管理页面，进行一次配置，连接成功后， 会保存配置信息。

2024-08-20 14:18 UTC, TechQuery approved these changes

2024-08-20 14:19 UTC, merged

2024-08-20 14:20 UTC, TechQuery commented
> 登录DashPress 的web 管理页面，进行一次配置，连接成功后， 会保存配置信息。

好的，那回馈一下上游脚手架吧。

2024-08-20 14:47 UTC, luojiyin1987 commented
https://github.com/dashpresshq/dashpress/discussions/88   对上游提出 issue。

2024-08-20 14:55 UTC, TechQuery commented
我说的是

> 上游脚手架

https://github.com/idea2app/REST-Node-ts

不是一个开源软件成品。